### ISSUE TITLE
Failure installation 

### ISSUE THREAD

**Issue by Graveyard9988** [maskedeken/shadow-tls-android#3]
![Screenshot_20230330_084045_Package installer](https://user-images.githubusercontent.com/116078041/228735628-eed1b884-5a64-40d0-a1aa-0a99408f3bb0.jpg)

**Comment by Graveyard9988** [comment]
Android 13 - arm64v8
Samsung a73

**Comment by maskedeken** [comment]
You are not encouraged to use this plugin, use Matsuri + sing-box instead

**Comment by Graveyard9988** [comment]
OK 
Thanks

**Comment by maskedeken** [comment]
try this [https://github.com/maskedeken/shadow-tls-android/releases/tag/v0.1.9](https://github.com/maskedeken/shadow-tls-android/releases/tag/v0.1.9)

**Comment by Graveyard9988** [comment]
Successfully installed! 🙏🏻
