### ISSUE TITLE
apk安装失败

### ISSUE THREAD

**Issue by liqsliu** [maskedeken/shadow-tls-android#4]
错误信息： `INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl242858316.tmp/base.apk (at Binary XML file line #44): com.github.shadowsocks.plugin.shadowtls.ConfigActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present`

系统：android 13
apk: shadow-tls-0.1.8-arm64-v8a-release.apk

**Comment by maskedeken** [comment]
try this [https://github.com/maskedeken/shadow-tls-android/releases/tag/v0.1.9](https://github.com/maskedeken/shadow-tls-android/releases/tag/v0.1.9)

**Comment by liqsliu** [comment]
> try this [https://github.com/maskedeken/shadow-tls-android/releases/tag/v0.1.9](https://github.com/maskedeken/shadow-tls-android/releases/tag/v0.1.9)

安装成功，非常感谢
